### ISSUE TITLE
Join screen issues

### ISSUE THREAD

**Issue by thiderman** [thiderman/drunkenfall#22]
* [x] Positions needs redesign now that we have nine archers
* [x] Joining does not properly redirect

**Comment by frontierpsycho** [comment]
I think I fixed the redirection issue. It's a matter of using proper named routes in vue to navigate to other views.

**Comment by frontierpsycho** [comment]
It's in my branch, though, I'll try to merge as soon as possible.

**Comment by thiderman** [comment]
Closed by #42
