### ISSUE TITLE
Modernize the frontend

### ISSUE THREAD

**Issue by thiderman** [thiderman/drunkenfall#30]
Since I am a JS pleb that didn't really write much of the language after 2012, a lot of the things in the current codebase is non-optimal and could use a refresher on how things actually should be these days.

We technically have no limits that drag us back - all users will use a less than six months old browser of the Chrome / Safari variety, and vue.js explicitly wants us to use ES6.

* [x] Utilize fat arrows instead of the `$vue = this` workaround I had to do
* [x] Make the `data()` methods on the components return an instance of the related class rather than just an empty object.
* [ ] Replace usage of the age-old `<div class="clear">` trick I've been using to be able to do `float` with endings.
* [x] Implement `set` and `get` methods where it makes sense.

All of these don't necessarily need to be in the same pull request. One PR per issue block is probably a good resolution for them. Just mention this issue number in it and it will be tracked in here automatically.

**Comment by thiderman** [comment]
@frontierpsycho: Could you take a swing at some of these?

**Comment by frontierpsycho** [comment]
I think I could! Not sure of the timeline, but I'll try.

**Comment by frontierpsycho** [comment]
Already started in #32.

**Comment by thiderman** [comment]
Since #32 is merged, I think there is no reason to keep this open. I'll close it!
