### ISSUE TITLE
Make WebSocket try to reconnect if disconnected

### ISSUE THREAD

**Issue by frontierpsycho** [thiderman/drunkenfall#46]
Don't go crazy, just try a few times every second after disconnection.

**Comment by thiderman** [comment]
Once ever 500ms is probably a good interval, potentially with some incremental backoff towards a couple of seconds if it is down for longer.

**Comment by frontierpsycho** [comment]
Also, I was thinking today that the connectivity status of the WebSocket could be shown in the header. If it's red, you know you need to reload.

**Comment by frontierpsycho** [comment]
#48

**Comment by thiderman** [comment]
Closed with the merging of #48.
