### ISSUE TITLE
Reverse the order of faces on the NextMatch screen

### ISSUE THREAD

**Issue by thiderman** [thiderman/drunkenfall#57]
During the tournament a lot of confusion arose because the players were to sit in front of the opposite order than the avatars on the screen.

This also lets us not have the indexes of tape on the floor.

* [x] Reverse [the player loop in NextMatch](https://github.com/thiderman/drunkenfall/blob/master/js/src/components/NextScreen.vue#L23-L25)
* [ ] Test it a few times

**Comment by frontierpsycho** [comment]
#65 .

**Comment by thiderman** [comment]
Just so you know, if you write "Closes #57" in either the commit message or the main PR message Github will automatically close issues when the PR is merged! :)

**Comment by frontierpsycho** [comment]
I didn't know, that's cool!
